# ¿Qué impulsa la inflación en Guatemala?

```{r}
pacman::p_load(tidyverse, rio, janitor, gganimate, ggtext, showtext)
```

#### Importando las bases de datos del INE

```{r}
from_ine <- 
  function(path) {
   import(path) |> 
    as_tibble() |> 
    clean_names() |> 
    select(year = ano,
           month = mes, 
           id = codigo,
           desc = descripcion,
           cpi = rep) |> 
    filter(str_length(id) == 2) |> 
    mutate(id = parse_number(id)) |> 
    mutate(desc = case_when(
      id == 1 ~ 'Alimentos',
      id == 2 ~ 'Licores',
      id == 3 ~ 'Vestimenta',
      id == 4 ~ 'Vivienda',
      id == 5 ~ 'Muebles',
      id == 6 ~ 'Salud',
      id == 7 ~ 'Transporte',
      id == 8 ~ 'Comunicaciones',
      id == 9 ~ 'Recreación',
      id == 10 ~ 'Educación',
      id == 11 ~ 'Restaurantes',
      id == 12 ~ 'Otros',
      TRUE ~ desc
    )) |> 
    mutate(month = as_factor(str_to_title(month)), 
           desc = as_factor(desc)) 
}
```

```{r}
year_2019 <- 'https://www.ine.gob.gt/sistema/uploads/2020/01/07/20200107183958VEdqlo5oBmhO5cvKTQhYRYj2D05gxCla.xls'
year_2020 <- 'https://www.ine.gob.gt/sistema/uploads/2021/01/07/20210107181008hU1E5mBYrw7qBqdWxofaZsj4rULMDiJe.xls'
year_2021 <- 'https://www.ine.gob.gt/sistema/uploads/2022/01/06/20220106212952xoNyfwpIfoBW1kdUPmnw7MVW98ZCTepI.xls'
year_2022 <- 'https://www.ine.gob.gt/sistema/uploads/2022/06/07/20220607184539YNiFivgBo98JEbaVMRUhaFG9wPw9ePe9.xls'
```

```{r}
cpi_raw <- 
  from_ine(year_2019) |> 
  bind_rows(from_ine(year_2020)) |> 
  bind_rows(from_ine(year_2021)) |> 
  bind_rows(from_ine(year_2022))
```

#### Expresando a los índices en tasas de cambio intermensual

```{r}
cpi <- 
  cpi_raw |> 
  select(!id) |> 
  pivot_wider(names_from = desc, 
              values_from = cpi) |> 
  mutate(across(where(is.numeric), ~ (log(.) - lag(log(.), 1)))) |> 
  filter(year != 2019) |>
  pivot_longer(!c(year, month), 
               names_to = 'expense', 
               values_to = 'rate') |> 
  mutate(expense = as_factor(expense),
         period = as_factor(paste(month, year)),
         label = paste0(round(rate * 100, 2), '%'))
```

#### Colores y tipografía

```{r}
text = '#0D0D0D'
main = '#F23E2E'
back = '#F2F2F2'

font_add_google('Nunito Sans', 'nunito')
showtext_auto()
```

#### Gráfico estático: Verificando los aspectos estéticos de la visualización

```{r}
cpi |> 
  filter(year == 2022 & month == 'Abril') |> 
  ggplot(aes(expense, rate)) +
  geom_col(fill = main, 
           alpha = .85) +
  geom_text(aes(expense, rate, label = label), 
            family = 'nunito',
            color = 'gray25',
            size = 3,
            vjust = ifelse(cpi[325:336,]$rate < 0, 1.5, -0.5)) +
  labs(title = "<span style = 'font-size: 29pt; color:#F23E2E'>—</span><br><b>¿Qué impulsa la inflación en Guatemala?</b><br><br>
    <span style = 'font-size: 12pt; color:#414141'>Tasa de cambio intermensual por categoría de gasto<br>del índice de precios al consumidor</span>",
       subtitle = 'Abril 2022',
       caption = 'Datos: Instituto Nacional de Estadística') +
  scale_y_continuous(labels = scales::percent) +
  coord_cartesian(clip = 'off') +
  theme(
    text = element_text(color = text),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks.length.x = unit(.3, 'line'),
    axis.ticks.y = element_blank(),
    plot.title = element_textbox_simple(
      size = 20,
      lineheight = 0.7,
      padding = margin(5.5, 5.5, 7, 5.5),
      margin = margin(0, 0, 7, 0)
    ),
    plot.title.position = 'plot',
    plot.subtitle = element_text(hjust = 1, 
                                 family = 'nunito',
                                 color = main),
    plot.caption = element_text(color = '#414141',
                                margin = unit(c(2.3, 0, 0, 0), 'line')),
    axis.text.x = element_text(angle = 45, vjust = .9, hjust = 1),
    panel.background = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.y = element_blank(),
    plot.background = element_rect(fill = back, color = back),
    plot.margin = unit(c(1.5, 1.5, 1.5, 1.5), 'line')
  )
```

#### Generando la animación

```{r}
plot <- 
  cpi |> 
  ggplot(aes(expense, rate)) +
  geom_col(fill = main, 
           alpha = .85) +
  geom_text(aes(expense, rate, label = label), 
            family = 'nunito',
            color = 'gray25',
            size = 3,
            vjust = ifelse(cpi$rate < 0, 1.5, -0.5)) +
  labs(title = "<span style = 'font-size: 29pt; color:#F23E2E'>—</span><br><b>¿Qué impulsa la inflación en Guatemala?</b><br><br>
    <span style = 'font-size: 12pt; color:#414141'>Tasa de cambio intermensual por categoría de gasto<br>del índice de precios al consumidor</span>",
       subtitle = '{closest_state}',
       caption = 'Datos: Instituto Nacional de Estadística') +
  scale_y_continuous(labels = scales::percent) +
  coord_cartesian(clip = 'off') +
  theme(
    text = element_text(color = text),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks.length.x = unit(.3, 'line'),
    axis.ticks.y = element_blank(),
    plot.title = element_textbox_simple(
      size = 20,
      lineheight = 0.7,
      padding = margin(5.5, 5.5, 7, 5.5),
      margin = margin(0, 0, 7, 0)
    ),
    plot.title.position = 'plot',
    plot.subtitle = element_text(hjust = 1, 
                                 family = 'nunito',
                                 color = main),
    plot.caption = element_text(color = '#414141',
                                margin = unit(c(2.3, 0, 0, 0), 'line')),
    axis.text.x = element_text(angle = 45, vjust = .9, hjust = 1),
    panel.background = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.y = element_blank(),
    plot.background = element_rect(fill = back, color = back),
    plot.margin = unit(c(1.5, 1.5, 1.5, 1.5), 'line')
  ) +
  transition_states(
    period,
    transition_length = 5,
    state_length = 2) +
  enter_grow(size = 1) + 
  exit_shrink(size = 2) +
  ease_aes('circular-in-out')

animation <- 
  animate(plot, 
          height = 6, width = 6, units = 'in', res = 300,
          nframes = 750, fps = 30, renderer = av_renderer())
```

```{r}
anim_save('animation.mp4', animation)
```
